name: CI

on:
  push:
    branches:
      - main
      - develop
      - "**" # all branches

jobs:
  TestClientAndServerWithCoverage:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install server dependencies
        working-directory: ./server
        run: npm install

      - name: Run server tests with coverage
        working-directory: ./server
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: npm test -- --coverage

      - name: Upload server coverage report
        uses: actions/upload-artifact@v4
        with:
          name: server-coverage
          path: ./server/coverage

      - name: Install client dependencies
        working-directory: ./client
        run: npm install

      - name: Run client tests with coverage
        working-directory: ./client
        run: npm test -- --coverage

      - name: Upload client coverage report
        uses: actions/upload-artifact@v4
        with:
          name: client-coverage
          path: ./client/coverage
